name: designs_hub
description: "A mobile application consisting of multiple designs templates"

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.2
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  firebase_analytics: ^10.8.10
  firebase_core: ^2.27.1
  firebase_crashlytics: ^3.4.19
  firebase_messaging: ^14.7.20
  flutter_local_notifications: ^17.0.0
  flutter_native_splash: ^2.3.10
  flutter_typeahead: ^5.2.0
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  google_fonts: ^6.2.1
  go_router: ^13.2.0
  json_annotation: ^4.8.1
  logger: ^2.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true